# Generated by Django 5.2 on 2025-05-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
